---
rabbitmq_users:
  - user: admin
    password: admin
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator
  - user: "{{ cindy_broker_user_name }}"
    password: "{{ cindy_broker_user_password }}"
    vhost: "{{ cindy_broker_vhost }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
  - rabbitmq_vhosts: ["{{ cindy_broker_vhost }}"]
