---
- name: install systemd service configuration
  tags: celery, systemd
  become: true
  template:
    src: etc/systemd/system/service.j2
    dest: "/etc/systemd/system/{{ worker_service_name }}.service"

- name: enable service
  tags: celery, systemd
  become: true
  systemd:
    name: "{{ worker_service_name }}"
    enabled: true
    state: restarted
    daemon_reload: true
