---
- hosts: all
  gather_facts: false

  vars:
    - repository_path: /home/vagrant/code

    - rabbitmq_use_ssl: false
    - rabbitmq_url: amqp://localhost

    - nofollow_app_development: true

    - nofollow_app_service_environment_file_path: /etc/nofollow.environment
    - nofollow_app_virtualenv_name: nofollow
    - nofollow_database_username: vagrant
    - nofollow_database_password: nofollow_web_db_pass
    - nofollow_app_static_root_path: /home/vagrant/nofollow_web/static
    - nofollow_app_emailer_address: noreply@nofollow_dev.example.com
    - nofollow_app_email_backend: django.core.mail.backends.console.EmailBackend
    - nofollow_app_log_folder_path: /home/vagrant/nofollow_web/logs
    - nofollow_app_log_path: "{{ nofollow_app_log_folder_path }}/app.log"
    - nofollow_app_secret_key: "this-is-an-insecure-secret-key"
    - nofollow_app_username: vagrant
    - nofollow_app_user_home_folder_path: /home/vagrant
    - nofollow_app_repository_folder_path: /home/vagrant/code
    - nofollow_app_code_folder_path: /home/vagrant/code/src
    - nofollow_worker_message_queue_password: insecurepasswd_rabbitmq


  roles:
    - role: rabbitmq
    - role: ANXS.postgresql
    - role: nofollow_webapp
    - role: nofollow_database
    - role: nofollow_worker

  pre_tasks:
  - include: setup.yml

  - name: add some lines to .bashrc
    lineinfile:
      name: /home/vagrant/.bashrc
      line: "{{ item }}"
    with_items:
      - "set -a && source {{ nofollow_app_service_environment_file_path }} && set +a"
      - "source /home/vagrant/.virtualenvs/{{ nofollow_app_virtualenv_name }}/bin/activate"
