---
- hosts: all
  gather_facts: false
  become: true

  vars:
    - cindy_app_development_mode: true
    - cindy_database_username: vagrant
    - cindy_database_password: insecurepasswd_database
    - cindy_app_email_backend: django.core.mail.backends.console.EmailBackend
    - cindy_app_secret_key: this_is_an_insecure_secret_key
    - cindy_app_username: vagrant
    - cindy_app_pypi_url: file:///home/vagrant/code/src
    - cindy_broker_user_password: insecurepasswd_rabbitmq

  roles:
    - role: stouts.rabbitmq
    - role: ANXS.postgresql
    - role: cindy_webapp
    - role: cindy_worker
    - role: cindy_database

  pre_tasks:
  - include: setup.yml

  - name: add some lines to .bashrc
    lineinfile:
      name: /home/vagrant/.bashrc
      line: "{{ item }}"
    with_items:
      - "set -a && source {{ cindy_app_service_environment_file_path }} && set +a"
      - "source /home/vagrant/.virtualenvs/{{ cindy_app_virtualenv_name }}/bin/activate"
