---
ca_certificate_path: /etc/ssl/certs/letsencrypt_ca.pem
certificate_store_live_dir: /etc/letsencrypt/live
certificate_store_dir: /etc/letsencrypt/archive
certificate_store_access_group_name: ssl-cert
ssl_dhparam_key_size: 2048
ssl_dhparam_file_location: /etc/ssl/certs/dhparam.pem

nginx_snippet_ssl_certificates_path: /etc/nginx/snippets/ssl_certificate_files.conf
nginx_snippet_ssl_params_path: /etc/nginx/snippets/ssl-params.conf
nginx_webroot_path: /var/www/html

cindy_nginx_site_name: cindy
