---
- name: create postgresql role
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ nofollow_database_username }}"
    password: "{{ nofollow_database_password }}"
    encrypted: true
    state: present
    role_attr_flags: LOGIN,SUPERUSER

- name: create webapp database
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ nofollow_database_name }}"
    owner: "{{ nofollow_database_username }}"
    encoding: UTF-8
    state: present
